import type { GetStaticProps, InferGetStaticPropsType, NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import { getSortedPostsData, Post } from '../lib/post';
import styles from '../styles/Home.module.css'
import utilStyles from '../styles/utils.module.css'

export const getStaticProps: GetStaticProps<{
  allPostsData: Post[],
  test: string | null,
  test2:  null,
  test3?:  null,
}> = async ({ params }) => {
  const allPostsData = getSortedPostsData();
  return {
    props: {
      allPostsData,
      test: null,
      test2: null,
    },
  };
}
type StaticPropsResult = ReturnType<typeof getStaticProps>
type Props = InferGetStaticPropsType<typeof getStaticProps>

const Home = (props: InferGetStaticPropsType<typeof getStaticProps>) => {
  const { allPostsData } = props;
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        {/* // Before
        <link
          href="https://fonts.googleapis.com/css2?family=Inter&display=optional"
          rel="stylesheet"
        />

        // After
        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
        <style data-href="https://fonts.googleapis.com/css2?family=Inter&display=optional">
          @font-face{font-family:'Inter'}
        </style> */}
      </Head>

      <main className={styles.main}>
      <section className={`${utilStyles.headingMd} ${utilStyles.padding1px}`}>
        <h2 className={utilStyles.headingLg}>Blog</h2>
        <ul className={utilStyles.list}>
          {allPostsData.map(({ id, date, title }) => (
            <li className={utilStyles.listItem} key={id}>
              {title}
              <br />
              {id}
              <br />
              {date}
            </li>
          ))}
        </ul>
      </section>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}

export default Home
